### ISSUE TITLE
ERROR in Ng2MobxModule is not an NgModule

### ISSUE THREAD

**Issue by janaagaard75** [500tech/ng2-mobx#11] opened 2017-01-25 19:04 UTC
After upgrading all the packages in the TodoMVC example I get the error `ERROR in Ng2MobxModule is not an NgModule` when starting the application. As far as I can tell the most common solution to this issue is to downgrade from TypeScript 2.1 to 2.0, but that doesn't fix this issue.

Here are the versions of the packages that I am using:

```json
"dependencies": {
  "@angular/common": "2.4.4",
  "@angular/compiler": "2.4.4",
  "@angular/core": "2.4.4",
  "@angular/forms": "2.4.4",
  "@angular/http": "2.4.4",
  "@angular/platform-browser": "2.4.4",
  "@angular/platform-browser-dynamic": "2.4.4",
  "@angular/router": "3.4.4",
  "core-js": "2.4.1",
  "mobx": "3.0.2",
  "ng2-mobx": "1.2.2",
  "rxjs": "5.0.3",
  "todomvc-app-css": "2.0.6",
  "todomvc-common": "1.0.3",
  "ts-helpers": "1.1.2",
  "zone.js": "0.7.6"
},
"devDependencies": {
  "@angular/compiler-cli": "2.4.4",
  "@types/jasmine": "2.5.41",
  "@types/node": "7.0.4",
  "angular-cli": "1.0.0-beta.26",
  "codelyzer": "2.0.0-beta.4",
  "jasmine-core": "2.5.2",
  "jasmine-spec-reporter": "3.2.0",
  "karma": "1.4.0",
  "karma-chrome-launcher": "2.0.0",
  "karma-cli": "1.0.1",
  "karma-jasmine": "1.1.0",
  "karma-remap-istanbul": "0.4.0",
  "protractor": "5.0.0",
  "ts-node": "2.0.0",
  "tslint": "4.3.1",
  "typescript": "2.0.10",
  "webdriver-manager": "11.1.1"
}
```

**Comment by adamkleingit** [comment] 2017-01-26 09:25
Hey,
I can't reproduce.
Using the above package json I'm actually getting a different warning but it works

**Comment by janaagaard75** [comment] 2017-01-26 10:18
It works, except the warning/error prevents auto-reloading the site. The whole repo is here. I'm using Yarn to install the packages, so I guess that should help making the error reproducible. I've switched back to TypeScript 2.1 since downgrading didn't work, and I might also have added a two peed dependencies that some package was complaining about.

https://github.com/janaagaard75/framework-investigations/tree/master/ng2-mobx-todomvc

(I hope it's okay that I copied the original files. Not too sure about how to handle these open source things correctly.)

**Comment by janaagaard75** [comment] 2017-01-27 14:00
Quick update: Upgrading the packages to the latest versions, mainly Angular bumped to v2.4.5, did not fix the issue.

**Comment by adamkleingit** [comment] 2017-02-04 11:31
Fixed in 1.2.3.
Please verify

**Comment by janaagaard75** [comment] 2017-02-05 09:38
Updated all the packages, and can confirm that error is gone now. 👍

**Comment by adamkleingit** [comment] 2017-02-05 11:26
Awesome

**Closed by adamkleingit** 2017-02-05 11:26 UTC
